public class Entry
{

    ////////// Member variables////////
    public string _date;

    public string _promptText;

    public string _entryText;


    /// Display method, it takes the prompt text from the member variable, which contains
    /// the random prompt generated by the GetRandomPrompt method.
    public void Display()
    {
        Console.WriteLine("");
        Console.WriteLine($"Date: {_date} - Prompt: {_promptText}");
        Console.WriteLine($"{_entryText}");
    }

}